import { createClient } from 'npm:@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL')!
  const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
  const notificationEmail = Deno.env.get('NOTIFICATION_EMAIL')

  if (!supabaseUrl || !supabaseServiceKey) {
    return new Response(JSON.stringify({ error: 'Server configuration error' }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }

  if (!notificationEmail) {
    return new Response(JSON.stringify({ error: 'NOTIFICATION_EMAIL not configured' }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }

  try {
    const body = await req.json()
    const { recipientEmail, recipientName, companyName, reportSummary, formData } = body

    if (!recipientEmail || !companyName) {
      return new Response(JSON.stringify({ error: 'Missing required fields' }), {
        status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      })
    }

    const supabase = createClient(supabaseUrl, supabaseServiceKey)
    const senderDomain = 'notify.corexoperations.com'
    const fromAddress = `Corex Operations <reports@${senderDomain}>`

    // ── Email 1: Report summary to client ──────────────────────────
    const clientHtml = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#ffffff;font-family:Arial,Helvetica,sans-serif;">
  <div style="max-width:600px;margin:0 auto;padding:40px 24px;">
    <div style="text-align:center;margin-bottom:32px;">
      <h1 style="color:#0f172a;font-size:28px;font-weight:800;margin:0 0 8px;">Your Operational Assessment</h1>
      <p style="color:#64748b;font-size:14px;margin:0;">${companyName}</p>
    </div>

    <div style="background:#f8fafc;border-radius:12px;padding:24px;margin-bottom:24px;">
      <h2 style="color:#0f172a;font-size:18px;font-weight:700;margin:0 0 8px;">Overall Score: ${reportSummary.overallScore}/100</h2>
      <p style="color:#3b82f6;font-size:14px;font-weight:600;margin:0 0 16px;">Maturity Level: ${reportSummary.maturityLabel}</p>
      <p style="color:#475569;font-size:14px;line-height:1.6;margin:0;">${reportSummary.executiveSummary}</p>
    </div>

    <div style="margin-bottom:24px;">
      <h3 style="color:#0f172a;font-size:16px;font-weight:700;margin:0 0 12px;">Category Scores</h3>
      ${reportSummary.categories.map((cat: { category: string; score: number; label: string }) => `
        <div style="display:flex;justify-content:space-between;padding:8px 0;border-bottom:1px solid #e2e8f0;">
          <span style="color:#475569;font-size:14px;">${cat.category}</span>
          <span style="color:#0f172a;font-size:14px;font-weight:600;">${cat.score}/100 (${cat.label})</span>
        </div>
      `).join('')}
    </div>

    <div style="margin-bottom:24px;">
      <h3 style="color:#0f172a;font-size:16px;font-weight:700;margin:0 0 12px;">Top Priority Actions</h3>
      ${reportSummary.priorityActions.map((a: { action: string; effort: string; impact: string }, i: number) => `
        <div style="padding:12px;background:#f8fafc;border-radius:8px;margin-bottom:8px;">
          <p style="color:#0f172a;font-size:14px;font-weight:600;margin:0 0 4px;">${i + 1}. ${a.action}</p>
          <p style="color:#64748b;font-size:12px;margin:0;">Effort: ${a.effort} · Impact: ${a.impact}</p>
        </div>
      `).join('')}
    </div>

    <div style="text-align:center;padding-top:24px;border-top:1px solid #e2e8f0;">
      <p style="color:#94a3b8;font-size:12px;margin:0;">This report was generated by Corex Operations</p>
    </div>
  </div>
</body>
</html>`

    // ── Email 2: New lead notification to owner ────────────────────
    const fd = formData || {}
    const leadHtml = `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#ffffff;font-family:Arial,Helvetica,sans-serif;">
  <div style="max-width:600px;margin:0 auto;padding:40px 24px;">
    <div style="background:#fef3c7;border-left:4px solid #f59e0b;padding:16px;border-radius:0 8px 8px 0;margin-bottom:24px;">
      <h1 style="color:#92400e;font-size:20px;font-weight:800;margin:0;">🔥 New Lead: ${companyName}</h1>
      <p style="color:#a16207;font-size:14px;margin:4px 0 0;">Score: ${reportSummary.overallScore}/100 · ${reportSummary.maturityLabel}</p>
    </div>

    <h2 style="color:#0f172a;font-size:18px;font-weight:700;margin:0 0 16px;">Contact Details</h2>
    <table style="width:100%;border-collapse:collapse;margin-bottom:24px;">
      <tr><td style="padding:8px 12px;color:#64748b;font-size:14px;border-bottom:1px solid #e2e8f0;width:140px;">Name</td><td style="padding:8px 12px;color:#0f172a;font-size:14px;font-weight:600;border-bottom:1px solid #e2e8f0;">${fd.name || 'N/A'}</td></tr>
      <tr><td style="padding:8px 12px;color:#64748b;font-size:14px;border-bottom:1px solid #e2e8f0;">Email</td><td style="padding:8px 12px;color:#0f172a;font-size:14px;font-weight:600;border-bottom:1px solid #e2e8f0;">${fd.email || recipientEmail}</td></tr>
      <tr><td style="padding:8px 12px;color:#64748b;font-size:14px;border-bottom:1px solid #e2e8f0;">Company</td><td style="padding:8px 12px;color:#0f172a;font-size:14px;font-weight:600;border-bottom:1px solid #e2e8f0;">${fd.companyName || companyName}</td></tr>
      <tr><td style="padding:8px 12px;color:#64748b;font-size:14px;border-bottom:1px solid #e2e8f0;">Website</td><td style="padding:8px 12px;color:#0f172a;font-size:14px;font-weight:600;border-bottom:1px solid #e2e8f0;">${fd.website || 'N/A'}</td></tr>
      <tr><td style="padding:8px 12px;color:#64748b;font-size:14px;border-bottom:1px solid #e2e8f0;">Revenue Band</td><td style="padding:8px 12px;color:#0f172a;font-size:14px;font-weight:600;border-bottom:1px solid #e2e8f0;">${fd.revenueBand || 'N/A'}</td></tr>
      <tr><td style="padding:8px 12px;color:#64748b;font-size:14px;border-bottom:1px solid #e2e8f0;">Team Size</td><td style="padding:8px 12px;color:#0f172a;font-size:14px;font-weight:600;border-bottom:1px solid #e2e8f0;">${fd.teamSize || 'N/A'}</td></tr>
    </table>

    <h2 style="color:#0f172a;font-size:18px;font-weight:700;margin:0 0 16px;">Quiz Responses</h2>
    <table style="width:100%;border-collapse:collapse;margin-bottom:24px;">
      <tr><td style="padding:8px 12px;color:#64748b;font-size:14px;border-bottom:1px solid #e2e8f0;width:140px;">Services</td><td style="padding:8px 12px;color:#0f172a;font-size:14px;border-bottom:1px solid #e2e8f0;">${(fd.services || []).join(', ') || 'N/A'}</td></tr>
      <tr><td style="padding:8px 12px;color:#64748b;font-size:14px;border-bottom:1px solid #e2e8f0;">PM Tool</td><td style="padding:8px 12px;color:#0f172a;font-size:14px;border-bottom:1px solid #e2e8f0;">${fd.pmTool || 'N/A'}</td></tr>
      <tr><td style="padding:8px 12px;color:#64748b;font-size:14px;border-bottom:1px solid #e2e8f0;">CRM</td><td style="padding:8px 12px;color:#0f172a;font-size:14px;border-bottom:1px solid #e2e8f0;">${fd.crm || 'N/A'}</td></tr>
      <tr><td style="padding:8px 12px;color:#64748b;font-size:14px;border-bottom:1px solid #e2e8f0;">Biggest Bottleneck</td><td style="padding:8px 12px;color:#0f172a;font-size:14px;border-bottom:1px solid #e2e8f0;">${fd.biggestBottleneck || 'N/A'}</td></tr>
      <tr><td style="padding:8px 12px;color:#64748b;font-size:14px;border-bottom:1px solid #e2e8f0;">Main Goal</td><td style="padding:8px 12px;color:#0f172a;font-size:14px;border-bottom:1px solid #e2e8f0;">${fd.mainGoal || 'N/A'}</td></tr>
      <tr><td style="padding:8px 12px;color:#64748b;font-size:14px;border-bottom:1px solid #e2e8f0;">Wants Help</td><td style="padding:8px 12px;color:#0f172a;font-size:14px;border-bottom:1px solid #e2e8f0;">${fd.implementationHelp === true ? 'Yes' : fd.implementationHelp === false ? 'No' : 'N/A'}</td></tr>
    </table>

    <h2 style="color:#0f172a;font-size:18px;font-weight:700;margin:0 0 16px;">Score Breakdown</h2>
    <table style="width:100%;border-collapse:collapse;">
      ${reportSummary.categories.map((cat: { category: string; score: number; label: string }) => `
        <tr>
          <td style="padding:8px 12px;color:#475569;font-size:14px;border-bottom:1px solid #e2e8f0;">${cat.category}</td>
          <td style="padding:8px 12px;color:#0f172a;font-size:14px;font-weight:600;border-bottom:1px solid #e2e8f0;text-align:right;">${cat.score}/100 (${cat.label})</td>
        </tr>
      `).join('')}
    </table>
  </div>
</body>
</html>`

    // Enqueue both emails via the transactional queue
    const messageId1 = crypto.randomUUID()
    const messageId2 = crypto.randomUUID()

    const { error: err1 } = await supabase.rpc('enqueue_email', {
      queue_name: 'transactional_emails',
      payload: {
        message_id: messageId1,
        to: recipientEmail,
        from: fromAddress,
        sender_domain: senderDomain,
        subject: `Your Operational Assessment — ${companyName}`,
        html: clientHtml,
        purpose: 'transactional',
        label: 'report-summary',
        queued_at: new Date().toISOString(),
      },
    })

    if (err1) {
      console.error('Failed to enqueue client email:', err1)
      throw new Error(`Failed to enqueue client email: ${err1.message}`)
    }

    const { error: err2 } = await supabase.rpc('enqueue_email', {
      queue_name: 'transactional_emails',
      payload: {
        message_id: messageId2,
        to: notificationEmail,
        from: fromAddress,
        sender_domain: senderDomain,
        subject: `🔥 New Lead: ${companyName} — Score ${reportSummary.overallScore}/100`,
        html: leadHtml,
        purpose: 'transactional',
        label: 'new-lead-notification',
        queued_at: new Date().toISOString(),
      },
    })

    if (err2) {
      console.error('Failed to enqueue lead notification:', err2)
      throw new Error(`Failed to enqueue lead notification: ${err2.message}`)
    }

    return new Response(JSON.stringify({ success: true }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : 'Unknown error'
    console.error('send-report-email error:', errorMessage)
    return new Response(JSON.stringify({ error: errorMessage }), {
      status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})
